### PR TITLE
Base point multiplication / Multiply scalar to generator

### PR DESCRIPTION
**Pull request by AHaliq**
Implemented multiplication function to generator : `alt_bn128_G1_bmul`

Useful for given private key `x`, derive its public key `g^x` via `alt_bn128_G1_bmul(x)`

Can also be used to derive point at infinity or identity via `alt_bn128_G1_bmul(zero)`

To be used in implementing a builtin in scilla

### CODE REVIEW

**Comment by anton-trunov** [comment]
Hi folks, can someone review this PR please? This is a blocker for us.

**Review by vaivaswatha — APPROVED** [review]

**Review by vaivaswatha — APPROVED** [review]
My approval is only a sanity check confirmation. Beyond that, I'm assuming that @AHaliq knows what's happening in the new function.

**Comment by vaivaswatha** [comment]
There's a merge conflict. Once that's fixed, I can merge this PR.

**Review by vaivaswatha — APPROVED** [review]

**Comment by AHaliq** [comment]
Closed due to refactoring `bmul` to be a stdlib instead of a builtin. Value of `one()` is captured as `alt_bn128_G1_g` in https://github.com/Zilliqa/scilla/pull/1026

**Pull request closed without merging**
